#!/bin/sh
#
# lcpgui        Starts labtester software.
#

start() {
	printf "start dbus: " 
	#check if dbus is started if not, start it! - is done with tmp file
	if [ ! -f "/tmp/dbus-started" ]; then
        	dbus-launch --sh-syntax > /tmp/dbus-started
        	eval `cat /tmp/dbus-started`
	else
        	#set only environment variables
        	eval `cat /tmp/dbus-started`
	fi

	/usr/libexec/bluetooth/obexd &

	if [ ! -d /mnt/lcp ]
	then 
		mkdir /mnt/lcp 
        chmod 777 /mnt/lcp
	fi

	if [ ! -d /opt/lcp ]
	then 
		mkdir /opt/lcp 
        chmod 777 /opt/lcp
	fi
	if [ ! -d /opt/lcp/setups ]
	then 
		mkdir /opt/lcp/setups
        chmod 777 /opt/lcp/setups
	fi

	if [ -e /dev/sda1 ]
	then
        	mount /dev/sda1 /mnt/lcp/
		if [ -f /mnt/lcp/lcpgui ]
		then
            cp -u /mnt/lcp/lcpgui /opt/lcp/lcpgui
			chmod 777 /opt/lcp/lcpgui
		fi
		if [ -f /mnt/lcp/lcp.ini ]
		then
            cp -u /mnt/lcp/lcp.ini /opt/lcp/lcp.ini
			chmod 777 /opt/lcp/lcp.ini
		fi
		if [ -f /mnt/lcp/machineCfg.ini ]
		then
            cp -u /mnt/lcp/machineCfg.ini /opt/lcp/machineCfg.ini
			chmod 777 /opt/lcp/machineCfg.ini
		fi	
		umount /dev/sda1
	fi

    if [ -e "/opt/lcp/lcpgui.xml" ]
	then
	 	echo "Restore trace (lcpgui.xml) file to /tmp"
	 	cp -p /opt/lcp/lcpgui.xml /tmp
	fi

	printf "Starting lcpgui: "
	export MasterVersion='test_1.0.0'
	export MasterTimestamp='2017-08-30 09:15'
	/opt/lcp/lcpgui &
	touch /opt/lcp/lock-lcpgui
	echo "OK"
}
stop() {
	printf "Stopping lcpgui: "
	killall lcpgui
	rm -f /opt/lcp/lock-lcpgui
	echo "OK"

	if [ -e "/tmp/lcpgui.xml" ]
	then
		echo "Make trace file (lcpgui.xml) persistent to /opt/lcp"
		cp -p /tmp/lcpgui.xml /opt/lcp/
	fi
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

