#!/bin/sh
#
# lcpgui        Starts labtester software.
#

start() {
	printf "start dbus: " 
	#check if dbus is started if not, start it! - is done with tmp file
	if [ ! -f "/tmp/dbus-started" ]; then
        	dbus-launch --sh-syntax > /tmp/dbus-started
        	eval `cat /tmp/dbus-started`
        	/usr/libexec/bluetooth/obexd &
		echo "started"
	else
        	#set only environment variables
        	eval `cat /tmp/dbus-started`
		echo "set enviremet variable"
	fi


	printf "Starting lcpgui: "
	/home/user/bin/lcpgui &
	touch /home/user/bin/lock-lcpgui
	echo "OK"
}
stop() {
	printf "Stopping lcpgui: "
	killall lcpgui
	rm -f /home/user/bin/lock-lcpgui
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

