#!/bin/sh
#
# lcpgui        Starts labtester software.
#

start() {
	printf "Starting lcpgui: "
	/home/user/bin/lcpgui &
	touch /home/user/bin/lock-lcpgui
	echo "OK"
}
stop() {
	printf "Stopping lcpgui: "
	killall lcpgui
	rm -f /home/user/bin/lock-lcpgui
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

