#!/bin/sh
#
# save/restore logging file....
#

case "$1" in
  start)
	if [ -e "/var/lcpgui.xml" ]
	then
	 	echo "Restore trace (lcpgui.xml) file to /tmp"
	 	cp -p /var/lcpgui.xml /tmp
	fi
	;;
  stop)
	if [ -e "/tmp/lcpgui.xml" ]
	then
		echo "Make trace file (lcpgui.xml) persistent to /var"
		cp -p /tmp/lcpgui.xml /var/
	fi
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

